### ISSUE TITLE
integer on 2 bytes

### ISSUE THREAD

**Issue by setop** [dadadel/binmake#1] opened 2017-01-30 15:09 UTC
with input :
```
decimal
26[2]
```
I expect `00000000: 1a00`, that is 2 bytes.
But I go `00000000: 1a00 0000`, that is 4 bytes.
Same appends when ask for only 1 byte, we got 4 bytes.

**Comment by dadadel** [comment] 2017-02-01 14:57
Hi @setop,
Thanks for reporting. Indeed, this input will produce an unexpected output as you said.

However, I have rewritten all the code in the branch called `regex` to which you can [have a look](https://github.com/dadadel/binmake/tree/regex).
In that new version, the problem is no more present.
I will merge it ASAP on master then I will close this issue.
Meanwhile you can use the `regex` branch.

**Comment by setop** [comment] 2017-02-01 16:10
In regex branch, it works great for 1,2,4.
Thanks

**Comment by dadadel** [comment] 2017-02-04 19:56
The branch `regex` has been merge into master. So the issue is fixed.

**Closed as completed by dadadel** 2017-02-04 19:56 UTC
